### ISSUE TITLE
Argly

### ISSUE THREAD

**Issue by austinkelleher** [CharlesWall/ec2-ssh-cli#2]
Use it

**Comment by austinkelleher** [comment]
Still interested in argly support. Thx. /cc @charlieduong94

**Comment by ctdio** [comment]
+1 @CharlesWall ?

**Comment by austinkelleher** [comment]
+1 @CharlesWall we need you. WE NEED THIS.

**Comment by Epitrochoid** [comment]
+1 @CharlesWall

**Comment by patrickhahn** [comment]
@CharlesWall please

**Comment by Druotic** [comment]
+1 @CharlesWall Pls.

**Comment by Greg-GB** [comment]
+1 @CharlesWall Yo Necessito.

**Comment by CharlesWall** [comment]
We really need this, @CharlesWall

**Comment by austinkelleher** [comment]
Spring cleaning. Please implement this though. I really really really need this. Please.
