### ISSUE TITLE
Thanks for this 

### ISSUE THREAD

**Issue by ctdio** [CharlesWall/ec2-ssh-cli#6]
![screen shot 2018-01-17 at 9 47 04 am](https://user-images.githubusercontent.com/9613701/35048555-6cf7df48-fb6b-11e7-9323-87dcca667033.png)

![tanks](https://media.giphy.com/media/GzCY1GMxqcQW4/giphy.gif)

cc @druotic @austinkelleher @epitrochoid @areese159

**Comment by austinkelleher** [comment]
I really needed this for SSHing into Marko. So for that:

![giphy](https://user-images.githubusercontent.com/3771924/35049172-21d08626-fb6d-11e7-948d-a8b7c65faf6d.gif)

**Comment by austin-rausch** [comment]
![5yzkz49chi501](https://user-images.githubusercontent.com/14016828/35049958-a489ad02-fb6f-11e7-886c-68550183b1ce.jpg)
We all make choices in life, my choice is to support Charles.
